### ISSUE TITLE
PyPI publishes don't wait on wheel build

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#1062] opened 2023-08-29 15:09 UTC
We suspect that the concurrency group of `{{ github.ref }}` isn't the same even thoug the SHA is.

**Comment by elliotcmorris** [comment] 2024-04-19 09:40
Dupe of https://github.com/OpenAssetIO/OpenAssetIO/issues/679

**Closed by elliotcmorris** 2024-04-19 09:40 UTC
Labels: ci
