### ISSUE TITLE
Support per-test/case settings in manager test harness

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/OpenAssetIO#775] opened 2022-12-05 10:19 UTC
## What

Allow the settings of the manager to be varied per test class/case when using the `openassetio.test.manager` framework to test the implementation of a `ManagerInterface`.

## Why

Currently, settings are global for all tests. This makes adding business-logic specific test cases [somewhat onerous](https://github.com/OpenAssetIO/OpenAssetIO-Manager-BAL/blob/63e3793a750649c3d55325edb695e8abb5d14520/tests/bal_business_logic_suite.py#L83) if they require variations in settings.

**Comment by foundrytom** [comment] 2022-12-05 10:19
Note: We need to see how often this comes up with real managers before prioritizing this work, it may be more specific to BAL's nature as a "puppet".

**Comment by feltech** [comment] 2024-05-21 15:11
Dupe of #473.

**Closed by feltech** 2024-05-21 15:11 UTC
Labels: test
